name: reusable workflow
description: Log a hello world message when invoked

on:
  workflow_call:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: log a message
        run: echo "Hello world!!!!!"
