name: reusable workflow
# this is an example of reusable workflow defined in local reository and refernced by other workflows in same repo only.
on:
  workflow_call:

jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
      - name: log a descriptor message
        run: echo "If you see this message, it means that local reusable workflow is successfully invoked!!"
