name: Test manual workflow git action

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run : |
          ls
          echo $CERT_PEM >> dummy_cert.txt
          ls
          mv dummy_cert.txt sample-file.txt
          cat sample-file.txt
      # composite action demo - action from another repo, action has a dedicated repo.
      - uses: adithyaamara/composite-action-test@v1
  CallLocalReusableAction:
    uses: ./.github/workflows/sample-reusabel.yml
  reusableSection:
  # Referring using relative path just like aboe job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # reusable workflow demo
      - uses: ./.github/actions/sample.yml
      
