name: Test manual workflow git action

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run : |
          ls
          echo $CERT_PEM >> dummy_cert.txt
          ls
          mv dummy_cert.txt sample-file.txt
          cat sample-file.txt
      # composite action demo
      - uses: adithyaamara/composite-action-test@v1
  reusable-section:
    # reusable workflow demo
    - uses: adithyaamara/HANA-Python/.github/workflows/reusable/hello-world.yml@main
