name: Test manual workflow git action

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: adithyaamara/HANA-Python/.github/worklflows/sample-reusable.yml@master
      - run : |
          ls
          echo $CERT_PEM >> dummy_cert.txt
          ls
          mv dummy_cert.txt sample-file.txt
          cat sample-file.txt
      # composite action demo - action from another repo, action has a dedicated repo.
      - uses: adithyaamara/composite-action-test@v1
  reusableSection:
  # name of action here must only be action.yml and should be placed in ./github/actions/
  # Not working - Fail
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # reusable workflow demo
      - uses: adithyaamara/HANA-Python/.github/actions/sample.yml@main
      
