name: Test manual workflow git action

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run : |
          ls
          echo ${{ secrets.CERT_PEM }} >> dummy_cert.txt
          ls
      
