name: Test manual workflow git action

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run : |
          echo "The Files in repo are : ."
          echo ${{ secrets.CERT_PEM }} > dummy_cert.pem
          ls
          cat dummy_cert.pem
      
